# Task 1

In [1]:
import pandas as pd

pd.__version__

'3.0.5'

# Task 2

In [7]:
from pathlib import Path

In [13]:
DATA_DIR = Path.cwd().parent.parent / 'datasets'

car_fuel = pd.read_csv(DATA_DIR / 'car_fuel_efficiency_2026.csv')
car_fuel.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [15]:
car_fuel.shape[0]

10000

# Task 3

In [17]:
fuel_types = car_fuel['fuel_type'].value_counts()
fuel_types

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [23]:
fuel_types.nunique()

3

# Task 4

In [24]:
missing_columns = car_fuel.isnull().sum()
missing_columns

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [30]:
(missing_columns > 0).sum()

np.int64(2)

# Task 5

In [32]:
asia_fuel = car_fuel[car_fuel['origin'] == 'Asia']
asia_fuel.head(3)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9

In [33]:
max_asia_fuel_eff = asia_fuel['fuel_efficiency_mpg'].max()
max_asia_fuel_eff

np.float64(41.2)